repos:
-   repo: https://github.com/python-poetry/poetry
    rev: ''  # add version here
    hooks:
    -   id: poetry-check
    -   id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]